---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-operator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "redis.opstreelabs.in"
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - statefulsets
      - persistentvolumeclaims
      - redis
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-operator-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: redis-operator
    namespace: redis-operator
roleRef:
  kind: Role
  name: redis-operator-role
  apiGroup: rbac.authorization.k8s.io